/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on Feb 16, 2011, 12:12:54 PM
 */

package watermaze_ver_3_0;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author Every one
 */
public class ImagePanel extends javax.swing.JPanel {
    private BufferedImage imgBuff = null;
    private int imgX = 0;
    private int imgY = 0;
    public ImagePanel() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
public void paint(Graphics g){
        if(imgBuff != null)
            g.drawImage(getImgBuff(), getImgX(), getImgY(),this);

}

    /**
     * @return the imgBuff
     */
    public BufferedImage getImgBuff() {
        return imgBuff;
    }

    /**
     * @param imgBuff the imgBuff to set
     */
    public void setImgBuff(BufferedImage imgBuff) {
        this.imgBuff = imgBuff;
    }

    /**
     * @return the imgX
     */
    public int getImgX() {
        return imgX;
    }

    /**
     * @param imgX the imgX to set
     */
    public void setImgX(int imgX) {
        this.imgX = imgX;
    }

    /**
     * @return the imgY
     */
    public int getImgY() {
        return imgY;
    }

    /**
     * @param imgY the imgY to set
     */
    public void setImgY(int imgY) {
        this.imgY = imgY;
    }
}
